### ISSUE TITLE
Icon stays grey

### ISSUE THREAD

**Issue by slick9115** [compvid30/scriptblock#2]
Windows 10 Pro; Chrome Version 44.0.2403.155 m
/*
Current Blocking Mode: Whitelist

List Stats

Total # Entries: 344

Space Occupied (dual-byte encoding): 5483 bytes / 5242880 bytes (0.10458 %)

Est. Space Occupied Encrypted (dual-byte encoding): 17546 bytes / 5242880 bytes (0.33466 %)

Est. Max. Entries: 102792

User Agent

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
*/

No matter what site I go to, the extension never changes to green or red. This happens whether the site is allowed, blocked, or temped.

-Steve

**Comment by compvid30** [comment]
Just fixed it, should be up soon.

**Comment by slick9115** [comment]
Wow, super fast. Thanks.

**Comment by restcure** [comment]
OS X 10.9.5, Version 44.0.2403.157 (64-bit)

All sites still greyed out for me.

**Comment by dcmargo54** [comment]
Windows 10, 64 bit

All sites grayed out for me also

**Comment by compvid30** [comment]
What version do you both use? If version 1.1 then uninstall and reinstall 1.2. it should be fixed. You can see the version in the options dialog.

**Comment by dcmargo54** [comment]
I'm using v1.2.0     I even uninstalled v1.2 and reinstalled it to see if that would help. It seemed to start after the most recent Chrome update, a couple or a few days ago.

**Comment by slick9115** [comment]
Ya. Actually mine hasn't changed either. I'm on 1.2.0

**Comment by dcmargo54** [comment]
I uninstalled, rebooted, then reinstalled v1.2 and all was normal. I tried entering websites manually and then the icon grayed out again. I reinstalled with just the default websites and it seems to be fine once more.  So far, it seems that if I allow websites as I encounter them, then the extension works as it should.

**Comment by slick9115** [comment]
On CentOS, Mac, and Windows 7 this works fine. Mine just stays grey in Windows 10, which was a clean install about 2wks ago. I will try @dcmargo54 's workaround and see if I can get my list in there somehow...

**Comment by dcmargo54** [comment]
Ever since I reinstalled ScriptBlock with just the default websites, and added websites (by clicking on the icon) only as I encounter them, I've had no problems at all.

**Comment by rowanthorpe** [comment]
I can also confirm this. On Windows Vista, whenever whitelist is manually edited then icon stays grey from then onwards (but still functions correctly, just always misleadingly grey). If whitelist is set back to default values or if extension is removed/reinstalled (and browser restarted) it behaves correctly again, as long as whitelist is only updated by clicking the popup while browsing, not by manual editing. Most likely when whitelist is manually updated the corresponding function to update the md5hash is missing or malfunctioning. At a glance it seems the error is somewhere in blockStart.js

**Comment by compvid30** [comment]
Thx for the tip. Unfortunately I have very limited time at the moment, becuase sit in a big project. I'll try to fix this as soon as possible. If some one find a fix please let me know. :)

**Comment by compvid30** [comment]
I found the bug in my lunch break. It is fixed now. You can edit the list again. :)

Just uploaded Version 1.3, should be available soon.

**Comment by dcmargo54** [comment]
Thanks for that, much appreciated...

**Comment by slick9115** [comment]
Yup. Looks good.
