### ISSUE TITLE
Trying to figure out how to sync

### ISSUE THREAD

**Issue by slick9115** [compvid30/scriptblock#4]
I have several computers and smart devices, etc... and I've been deduping and syncing my whitelist via Google Drive, manually. I read about the password and it seems like it's supposed to sync if the passwords are the same, but it does not. I may be misunderstanding the point of that outside of it protecting against malicious config changes, but if I could get some help with this it would be greatly appreciated. Otherwise it should be feature request...

**Comment by compvid30** [comment]
There is no way to sync at the moment.

**Comment by slick9115** [comment]
Will do. Thanks.

**Comment by MikaelElkiaer** [comment]
Wouldn't it be possible to sync, as @slick9115 wishes, with the use of chrome.storage?
https://developer.chrome.com/extensions/storage
